version: '3.8'

services:
  back_base_arq:
    image: back_base_arq
    ports:
      - "3030:3030"
    environment:
      DATABASE_HOST: postgresql
      DATABASE_USER: enmarcm
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: postgredb
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  front_arq:
    image: front_arq
    ports:
      - "5174:5174"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  postgresql:
    image: postgresql
    environment:
      POSTGRES_USER: enmarcm
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgredb
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure